### ISSUE TITLE
Add option to ignore SSL certificates on the webhooks

### ISSUE THREAD

**Issue by jeremyrichardmann** [saqura/xmppwb#3]
New issue to add an Unsafe option, to allow bypass of SSL validation.

I have the code working with a -u option on the command line, just need permission to push a branch so you can merge.

**Comment by saqura** [comment]
Thanks for your interest in contributing! The general workflow to contribute changes on github is to fork the project, push the changes to your own fork, and then create a pull request using the github UI.

> only issue I have now is it not trusting SSL certificate for the rocket.chat server, though it does have a valid cert

Can you post the exact error you get (using the -d and -v flags for verbose debugging)? Currently the [default python SSL context](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) is used, which uses the [system's default CA certificates](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_default_certs). Maybe python cannot find the default certificates. The issue might also be that your server is using an old SSL version that is not supported (SSLv2 and SSLv3, which are deprecated).

Instead of bypassing SSL validation I would rather add an option to specify the path to the server certificate though since that should work in case Python cannot validate it using the default certificates or in case of self-signed certificates.

**Comment by jeremyrichardmann** [comment]
Looks like that did it, adding the trusted roots to /etc/pki/ca-trust/source/anchors and running update-ca-trust worked (Centos7)

**Comment by saqura** [comment]
Great that this fixed it. I think this is a better solution than not verifying the certificate at all.

**Comment by saqura** [comment]
There is now a [cafile option](https://github.com/saqura/xmppwb/blob/master/CONFIGURATION.rst#the-outgoing_webhooks-section-of-a-bridge) to explicitely specify the certificate chain used for validating the outgoing webhook server.
